name: Nightly Liveness Check

#on: push
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker/setup-buildx-action@master
    - name: check sites that should be live
      run: |
        pip install curl_cffi
        ./check.py || ./check.py || ./check.py || ./check.py
